name: NoFurnaceExp
main: com.vk2gpz.nofurnaceexp.NoFurnaceExp
version: ${project.version}
description: No exp from furnace
author: vk2gpz

commands:
  nfexp:
    description: Toggle no exp from furnace.
    usage: /nfexp
    permission: nfexp.use
    permission-message: You do not have /<permission>
    usage: "Syntax error! Perhaps you meant /<command> ?"

permissions:
  nfexp.*:
    children:
      nfexp.toggle: true
  nfexp.toggle:
    default: op
